// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// This configuration captures the details required to render an authorization
/// link for the OAuth Authorization Code Flow.
public struct AuthorizationCodeLink: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The base URI the user must click to trigger the authorization code login
  /// flow.
  public var uri: Swift.String = Swift.String()

  /// The scopes for which the user will authorize GCP Connectors on the
  /// connector data source.
  public var scopes: [Swift.String] = []

  /// The client ID assigned to the GCP Connectors OAuth app for the connector
  /// data source.
  public var clientId: Swift.String = Swift.String()

  /// Whether to enable PKCE for the auth code flow.
  public var enablePkce: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `AuthorizationCodeLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthorizationCodeLink().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.AuthorizationCodeLink"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
