// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// AuthConfigTemplate defines required field over an authentication type.
public struct AuthConfigTemplate: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The type of authentication configured.
  public var authType: AuthType = AuthType()

  /// Config variables to describe an `AuthConfig` for a `Connection`.
  public var configVariableTemplates: [ConfigVariableTemplate] = []

  /// Display name for authentication template.
  public var displayName: Swift.String = Swift.String()

  /// Connector specific description for an authentication template.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `AuthConfigTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthConfigTemplate().with { $0.authType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.AuthConfigTemplate"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
