// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// AuthConfig defines details of a authentication type.
public struct AuthConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The type of authentication configured.
  public var authType: AuthType = AuthType()

  /// List containing additional auth configs.
  public var additionalVariables: [ConfigVariable] = []

  /// Supported auth types.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `AuthConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthConfig().with { $0.authType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case authType = "authType"
    case userPassword = "userPassword"
    case oauth2JwtBearer = "oauth2JwtBearer"
    case oauth2ClientCredentials = "oauth2ClientCredentials"
    case sshPublicKey = "sshPublicKey"
    case additionalVariables = "additionalVariables"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.authType = try container.decode(AuthType.self, forKey: .authType)
    self.additionalVariables = try container.decode(
      [ConfigVariable].self, forKey: .additionalVariables)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let userPassword = try container.decodeIfPresent(
      AuthConfig.UserPassword?.self, forKey: .userPassword)
    {
      try typeCheckAndSet(.userPassword(userPassword))
    }
    if let oauth2JwtBearer = try container.decodeIfPresent(
      AuthConfig.Oauth2JwtBearer?.self, forKey: .oauth2JwtBearer)
    {
      try typeCheckAndSet(.oauth2JwtBearer(oauth2JwtBearer))
    }
    if let oauth2ClientCredentials = try container.decodeIfPresent(
      AuthConfig.Oauth2ClientCredentials?.self, forKey: .oauth2ClientCredentials)
    {
      try typeCheckAndSet(.oauth2ClientCredentials(oauth2ClientCredentials))
    }
    if let sshPublicKey = try container.decodeIfPresent(
      AuthConfig.SshPublicKey?.self, forKey: .sshPublicKey)
    {
      try typeCheckAndSet(.sshPublicKey(sshPublicKey))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.authType, forKey: .authType)
    try container.encode(self.additionalVariables, forKey: .additionalVariables)

    if let choice = self.type {
      switch choice {
      case .userPassword(let value):
        try container.encode(value, forKey: .userPassword)
      case .oauth2JwtBearer(let value):
        try container.encode(value, forKey: .oauth2JwtBearer)
      case .oauth2ClientCredentials(let value):
        try container.encode(value, forKey: .oauth2ClientCredentials)
      case .sshPublicKey(let value):
        try container.encode(value, forKey: .sshPublicKey)
      }
    }
  }

  /// Parameters to support Username and Password Authentication.
  public struct UserPassword: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Username.
    public var username: Swift.String = Swift.String()

    /// Secret version reference containing the password.
    public var password: Secret? = nil

    /// Initialize a new instance of `UserPassword`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserPassword().with { $0.username = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.UserPassword"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters to support JSON Web Token (JWT) Profile for Oauth 2.0
  /// Authorization Grant based authentication.
  /// See https://tools.ietf.org/html/rfc7523 for more details.
  public struct Oauth2JwtBearer: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Secret version reference containing a PKCS#8 PEM-encoded private
    /// key associated with the Client Certificate. This private key will be
    /// used to sign JWTs used for the jwt-bearer authorization grant.
    /// Specified in the form as: `projects/*/secrets/*/versions/*`.
    public var clientKey: Secret? = nil

    /// JwtClaims providers fields to generate the token.
    public var jwtClaims: AuthConfig.Oauth2JwtBearer.JwtClaims? = nil

    /// Initialize a new instance of `Oauth2JwtBearer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Oauth2JwtBearer().with { $0.clientKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// JWT claims used for the jwt-bearer authorization grant.
    public struct JwtClaims: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Value for the "iss" claim.
      public var issuer: Swift.String = Swift.String()

      /// Value for the "sub" claim.
      public var subject: Swift.String = Swift.String()

      /// Value for the "aud" claim.
      public var audience: Swift.String = Swift.String()

      /// Initialize a new instance of `JwtClaims`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = JwtClaims().with { $0.issuer = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.Oauth2JwtBearer.JwtClaims"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.Oauth2JwtBearer"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters to support Oauth 2.0 Client Credentials Grant Authentication.
  /// See https://tools.ietf.org/html/rfc6749#section-1.3.4 for more details.
  public struct Oauth2ClientCredentials: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The client identifier.
    public var clientId: Swift.String = Swift.String()

    /// Secret version reference containing the client secret.
    public var clientSecret: Secret? = nil

    /// Initialize a new instance of `Oauth2ClientCredentials`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Oauth2ClientCredentials().with { $0.clientId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.Oauth2ClientCredentials"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters to support Ssh public key Authentication.
  public struct SshPublicKey: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The user account used to authenticate.
    public var username: Swift.String = Swift.String()

    /// SSH Client Cert. It should contain both public and private key.
    public var sshClientCert: Secret? = nil

    /// Format of SSH Client cert.
    public var certType: Swift.String = Swift.String()

    /// Password (passphrase) for ssh client certificate if it has one.
    public var sshClientCertPass: Secret? = nil

    /// Initialize a new instance of `SshPublicKey`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SshPublicKey().with { $0.username = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.SshPublicKey"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Supported auth types.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// UserPassword.
    indirect case userPassword(AuthConfig.UserPassword?)
    /// Oauth2JwtBearer.
    indirect case oauth2JwtBearer(AuthConfig.Oauth2JwtBearer?)
    /// Oauth2ClientCredentials.
    indirect case oauth2ClientCredentials(AuthConfig.Oauth2ClientCredentials?)
    /// SSH Public Key.
    indirect case sshPublicKey(AuthConfig.SshPublicKey?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
