// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ConfigVariable represents a configuration variable present in a Connection.
/// or AuthConfig.
public struct ConfigVariable: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Key of the config variable.
  public var key: Swift.String = Swift.String()

  /// Value type of the config variable.
  public var value: OneOf_Value? = nil

  /// Initialize a new instance of `ConfigVariable`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigVariable().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case key = "key"
    case intValue = "intValue"
    case boolValue = "boolValue"
    case stringValue = "stringValue"
    case secretValue = "secretValue"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.key = try container.decode(Swift.String.self, forKey: .key)

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let intValue = try container.decodeIfPresent(Swift.Int64.self, forKey: .intValue) {
      try valueCheckAndSet(.intValue(intValue))
    }
    if let boolValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolValue) {
      try valueCheckAndSet(.boolValue(boolValue))
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try valueCheckAndSet(.stringValue(stringValue))
    }
    if let secretValue = try container.decodeIfPresent(Secret?.self, forKey: .secretValue) {
      try valueCheckAndSet(.secretValue(secretValue))
    }
    self.value = value
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)

    if let choice = self.value {
      switch choice {
      case .intValue(let value):
        try container.encode(value, forKey: .intValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .secretValue(let value):
        try container.encode(value, forKey: .secretValue)
      }
    }
  }

  /// Value type of the config variable.
  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// Value is an integer
    case intValue(Swift.Int64)
    /// Value is a bool.
    case boolValue(Swift.Bool)
    /// Value is a string.
    case stringValue(Swift.String)
    /// Value is a secret.
    indirect case secretValue(Secret?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.ConfigVariable"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
