// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ConfigVariableTemplate provides metadata about a `ConfigVariable` that is
/// used in a Connection.
public struct ConfigVariableTemplate: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Key of the config variable.
  public var key: Swift.String = Swift.String()

  /// Type of the parameter: string, int, bool etc.
  /// consider custom type for the benefit for the validation.
  public var valueType: ConfigVariableTemplate.ValueType = ConfigVariableTemplate.ValueType()

  /// Display name of the parameter.
  public var displayName: Swift.String = Swift.String()

  /// Description.
  public var description: Swift.String = Swift.String()

  /// Regular expression in RE2 syntax used for validating the `value` of a
  /// `ConfigVariable`.
  public var validationRegex: Swift.String = Swift.String()

  /// Flag represents that this `ConfigVariable` must be provided for a
  /// connection.
  public var `required`: Swift.Bool = Swift.Bool()

  /// Role grant configuration for the config variable.
  public var roleGrant: RoleGrant? = nil

  /// Enum options. To be populated if `ValueType` is `ENUM`
  public var enumOptions: [EnumOption] = []

  /// Authorization code link options. To be populated if `ValueType` is
  /// `AUTHORIZATION_CODE`
  public var authorizationCodeLink: AuthorizationCodeLink? = nil

  /// State of the config variable.
  public var state: ConfigVariableTemplate.State = ConfigVariableTemplate.State()

  /// Indicates if current template is part of advanced settings
  public var isAdvanced: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ConfigVariableTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigVariableTemplate().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case key = "key"
    case valueType = "valueType"
    case displayName = "displayName"
    case description = "description"
    case validationRegex = "validationRegex"
    case `required` = "required"
    case roleGrant = "roleGrant"
    case enumOptions = "enumOptions"
    case authorizationCodeLink = "authorizationCodeLink"
    case state = "state"
    case isAdvanced = "isAdvanced"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.key = try container.decode(Swift.String.self, forKey: .key)
    self.valueType = try container.decode(ConfigVariableTemplate.ValueType.self, forKey: .valueType)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.validationRegex = try container.decode(Swift.String.self, forKey: .validationRegex)
    self.`required` = try container.decode(Swift.Bool.self, forKey: .`required`)
    self.roleGrant = try container.decodeIfPresent(RoleGrant.self, forKey: .roleGrant)
    self.enumOptions = try container.decode([EnumOption].self, forKey: .enumOptions)
    self.authorizationCodeLink = try container.decodeIfPresent(
      AuthorizationCodeLink.self, forKey: .authorizationCodeLink)
    self.state = try container.decode(ConfigVariableTemplate.State.self, forKey: .state)
    self.isAdvanced = try container.decode(Swift.Bool.self, forKey: .isAdvanced)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.valueType, forKey: .valueType)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.validationRegex, forKey: .validationRegex)
    try container.encode(self.`required`, forKey: .`required`)
    try container.encode(self.roleGrant, forKey: .roleGrant)
    try container.encode(self.enumOptions, forKey: .enumOptions)
    try container.encode(self.authorizationCodeLink, forKey: .authorizationCodeLink)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.isAdvanced, forKey: .isAdvanced)
  }

  /// ValueType indicates the data type of the value.
  public enum ValueType: Codable, Equatable, Sendable {
    /// Value type is not specified.
    case unspecified
    /// Value type is string.
    case string
    /// Value type is integer.
    case int
    /// Value type is boolean.
    case bool
    /// Value type is secret.
    case secret
    /// Value type is enum.
    case `enum`
    /// Value type is authorization code.
    case authorizationCode
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 1
      case .int: return 2
      case .bool: return 3
      case .secret: return 4
      case .`enum`: return 5
      case .authorizationCode: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VALUE_TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .int: return "INT"
      case .bool: return "BOOL"
      case .secret: return "SECRET"
      case .`enum`: return "ENUM"
      case .authorizationCode: return "AUTHORIZATION_CODE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ValueType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VALUE_TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "INT": self = .int
      case "BOOL": self = .bool
      case "SECRET": self = .secret
      case "ENUM": self = .`enum`
      case "AUTHORIZATION_CODE": self = .authorizationCode
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ValueType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .string
      case 2: self = .int
      case 3: self = .bool
      case 4: self = .secret
      case 5: self = .`enum`
      case 6: self = .authorizationCode
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .string: return try container.encode(1)
      case .int: return try container.encode(2)
      case .bool: return try container.encode(3)
      case .secret: return try container.encode(4)
      case .`enum`: return try container.encode(5)
      case .authorizationCode: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Indicates the state of the config variable.
  public enum State: Codable, Equatable, Sendable {
    /// Status is unspecified.
    case unspecified
    /// Config variable is active
    case active
    /// Config variable is deprecated.
    case deprecated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .deprecated: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .deprecated: return "DEPRECATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "DEPRECATED": self = .deprecated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .deprecated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .deprecated: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.ConfigVariableTemplate"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
