// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol ConnectorsStub: Sendable {
    func listConnections(
      request: ListConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectionsResponse

    func getConnection(
      request: GetConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Connection

    func createConnection(
      request: CreateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateConnection(
      request: UpdateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listProviders(
      request: ListProvidersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListProvidersResponse

    func getProvider(
      request: GetProviderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Provider

    func listConnectors(
      request: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectorsResponse

    func getConnector(
      request: GetConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Connector

    func listConnectorVersions(
      request: ListConnectorVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse

    func getConnectorVersion(
      request: GetConnectorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ConnectorVersion

    func getConnectionSchemaMetadata(
      request: GetConnectionSchemaMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata

    func refreshConnectionSchemaMetadata(
      request: RefreshConnectionSchemaMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRuntimeEntitySchemas(
      request: ListRuntimeEntitySchemasRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse

    func listRuntimeActionSchemas(
      request: ListRuntimeActionSchemasRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse

    func getRuntimeConfig(
      request: GetRuntimeConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.RuntimeConfig

    func getGlobalSettings(
      request: GetGlobalSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Settings

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
