// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ConnectorsLogging: ConnectorsStub {
    let inner: any ConnectorsStub
    let logger: Logger

    public init(_ inner: any ConnectorsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-connectors-v1"
      logger[metadataKey: "gcp.client.service"] = "connectors"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Connectors"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listConnections(
      request: ListConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnections",
        action: {
          (r: ListConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ListConnectionsResponse
          in
          return try await self.inner.listConnections(request: r, options: o)
        })
    }

    public func getConnection(
      request: GetConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Connection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnection",
        action: {
          (r: GetConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.Connection
          in
          return try await self.inner.getConnection(request: r, options: o)
        })
    }

    public func createConnection(
      request: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConnection",
        action: {
          (r: CreateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConnection(request: r, options: o)
        })
    }

    public func updateConnection(
      request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConnection",
        action: {
          (r: UpdateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConnection(request: r, options: o)
        })
    }

    public func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConnection",
        action: {
          (r: DeleteConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConnection(request: r, options: o)
        })
    }

    public func listProviders(
      request: ListProvidersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListProvidersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listProviders",
        action: {
          (r: ListProvidersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ListProvidersResponse
          in
          return try await self.inner.listProviders(request: r, options: o)
        })
    }

    public func getProvider(
      request: GetProviderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Provider {
      try await self._intercept(
        request: request,
        options: options,
        name: "getProvider",
        action: {
          (r: GetProviderRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.Provider
          in
          return try await self.inner.getProvider(request: r, options: o)
        })
    }

    public func listConnectors(
      request: ListConnectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnectors",
        action: {
          (r: ListConnectorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ListConnectorsResponse
          in
          return try await self.inner.listConnectors(request: r, options: o)
        })
    }

    public func getConnector(
      request: GetConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Connector {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnector",
        action: {
          (r: GetConnectorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.Connector
          in
          return try await self.inner.getConnector(request: r, options: o)
        })
    }

    public func listConnectorVersions(
      request: ListConnectorVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnectorVersions",
        action: {
          (r: ListConnectorVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse
          in
          return try await self.inner.listConnectorVersions(request: r, options: o)
        })
    }

    public func getConnectorVersion(
      request: GetConnectorVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ConnectorVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnectorVersion",
        action: {
          (r: GetConnectorVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ConnectorVersion
          in
          return try await self.inner.getConnectorVersion(request: r, options: o)
        })
    }

    public func getConnectionSchemaMetadata(
      request: GetConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnectionSchemaMetadata",
        action: {
          (r: GetConnectionSchemaMetadataRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata
          in
          return try await self.inner.getConnectionSchemaMetadata(request: r, options: o)
        })
    }

    public func refreshConnectionSchemaMetadata(
      request: RefreshConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "refreshConnectionSchemaMetadata",
        action: {
          (r: RefreshConnectionSchemaMetadataRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.refreshConnectionSchemaMetadata(request: r, options: o)
        })
    }

    public func listRuntimeEntitySchemas(
      request: ListRuntimeEntitySchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRuntimeEntitySchemas",
        action: {
          (r: ListRuntimeEntitySchemasRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse
          in
          return try await self.inner.listRuntimeEntitySchemas(request: r, options: o)
        })
    }

    public func listRuntimeActionSchemas(
      request: ListRuntimeActionSchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRuntimeActionSchemas",
        action: {
          (r: ListRuntimeActionSchemasRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse
          in
          return try await self.inner.listRuntimeActionSchemas(request: r, options: o)
        })
    }

    public func getRuntimeConfig(
      request: GetRuntimeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.RuntimeConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRuntimeConfig",
        action: {
          (r: GetRuntimeConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.RuntimeConfig
          in
          return try await self.inner.getRuntimeConfig(request: r, options: o)
        })
    }

    public func getGlobalSettings(
      request: GetGlobalSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Settings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGlobalSettings",
        action: {
          (r: GetGlobalSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConnectorsV1.Settings
          in
          return try await self.inner.getGlobalSettings(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
