// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ConnectorVersion indicates a specific version of a connector.
public struct ConnectorVersion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the Version.
  /// Format:
  /// projects/{project}/locations/{location}/providers/{provider}/connectors/{connector}/versions/{version}
  /// Only global location is supported for Connector resource.
  public var name: Swift.String = Swift.String()

  /// Output only. Created time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Updated time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Flag to mark the version indicating the launch stage.
  public var launchStage: LaunchStage = LaunchStage()

  /// Output only. ReleaseVersion of the connector, for example: "1.0.1-alpha".
  public var releaseVersion: Swift.String = Swift.String()

  /// Output only. List of auth configs supported by the Connector Version.
  public var authConfigTemplates: [AuthConfigTemplate] = []

  /// Output only. List of config variables needed to create a connection.
  public var configVariableTemplates: [ConfigVariableTemplate] = []

  /// Output only. Information about the runtime features supported by the
  /// Connector.
  public var supportedRuntimeFeatures: SupportedRuntimeFeatures? = nil

  /// Output only. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Configuration for Egress Control.
  public var egressControlConfig: EgressControlConfig? = nil

  /// Output only. Role grant configurations for this connector version.
  public var roleGrants: [RoleGrant] = []

  /// Output only. Role grant configuration for this config variable. It will be
  /// DEPRECATED soon.
  public var roleGrant: RoleGrant? = nil

  /// Output only. Ssl configuration supported by the Connector.
  public var sslConfigTemplate: SslConfigTemplate? = nil

  /// Initialize a new instance of `ConnectorVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectorVersion().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.ConnectorVersion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
