// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Connection represents an instance of connector.
public struct Connection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the Connection.
  /// Format: projects/{project}/locations/{location}/connections/{connection}
  public var name: Swift.String = Swift.String()

  /// Output only. Created time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Updated time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Description of the resource.
  public var description: Swift.String = Swift.String()

  /// Required. Connector version on which the connection is created.
  /// The format is:
  /// projects/*/locations/*/providers/*/connectors/*/versions/*
  /// Only global location is supported for ConnectorVersion resource.
  public var connectorVersion: Swift.String = Swift.String()

  /// Output only. Current status of the connection.
  public var status: ConnectionStatus? = nil

  /// Optional. Configuration for configuring the connection with an external
  /// system.
  public var configVariables: [ConfigVariable] = []

  /// Optional. Configuration for establishing the connection's authentication
  /// with an external system.
  public var authConfig: AuthConfig? = nil

  /// Optional. Configuration that indicates whether or not the Connection can be
  /// edited.
  public var lockConfig: LockConfig? = nil

  /// Optional. Configuration of the Connector's destination. Only accepted for
  /// Connectors that accepts user defined destination(s).
  public var destinationConfigs: [DestinationConfig] = []

  /// Output only. GCR location where the runtime image is stored.
  /// formatted like: gcr.io/{bucketName}/{imageName}
  public var imageLocation: Swift.String = Swift.String()

  /// Optional. Service account needed for runtime plane to access GCP resources.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. The name of the Service Directory service name. Used for
  /// Private Harpoon to resolve the ILB address.
  /// e.g.
  /// "projects/cloud-connectors-e2e-testing/locations/us-central1/namespaces/istio-system/services/istio-ingressgateway-connectors"
  public var serviceDirectory: Swift.String = Swift.String()

  /// Output only. GCR location where the envoy image is stored.
  /// formatted like: gcr.io/{bucketName}/{imageName}
  public var envoyImageLocation: Swift.String = Swift.String()

  /// Optional. Suspended indicates if a user has suspended a connection or not.
  public var suspended: Swift.Bool = Swift.Bool()

  /// Optional. Node configuration for the connection.
  public var nodeConfig: NodeConfig? = nil

  /// Optional. Ssl config of a connection
  public var sslConfig: SslConfig? = nil

  /// Initialize a new instance of `Connection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.Connection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
