// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Egress control config for connector runtime. These configurations define the
/// rules to identify which outbound domains/hosts needs to be whitelisted. It
/// may be a static information for a particular connector version or it is
/// derived from the configurations provided by the customer in Connection
/// resource.
public struct EgressControlConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  public var oneofBackends: OneOf_OneofBackends? = nil

  /// Initialize a new instance of `EgressControlConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EgressControlConfig().with { $0.backends = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case backends = "backends"
    case extractionRules = "extractionRules"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var oneofBackends: OneOf_OneofBackends? = nil
    let oneofBackendsCheckAndSet = {
      if oneofBackends != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'oneofBackends'"))
      }
      oneofBackends = $0
    }
    if let backends = try container.decodeIfPresent(Swift.String.self, forKey: .backends) {
      try oneofBackendsCheckAndSet(.backends(backends))
    }
    if let extractionRules = try container.decodeIfPresent(
      ExtractionRules?.self, forKey: .extractionRules)
    {
      try oneofBackendsCheckAndSet(.extractionRules(extractionRules))
    }
    self.oneofBackends = oneofBackends
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.oneofBackends {
      switch choice {
      case .backends(let value):
        try container.encode(value, forKey: .backends)
      case .extractionRules(let value):
        try container.encode(value, forKey: .extractionRules)
      }
    }
  }

  public enum OneOf_OneofBackends: Codable, Equatable, Sendable {
    /// Static Comma separated backends which are common for all Connection
    /// resources. Supported formats for each backend are host:port or just
    /// host (host can be ip address or domain name).
    case backends(Swift.String)
    /// Extractions Rules to extract the backends from customer provided
    /// configuration.
    indirect case extractionRules(ExtractionRules?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.EgressControlConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
