// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Provider indicates the owner who provides the connectors.
public struct Provider: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the Provider.
  /// Format: projects/{project}/locations/{location}/providers/{provider}
  /// Only global location is supported for Provider resource.
  public var name: Swift.String = Swift.String()

  /// Output only. Created time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Updated time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Link to documentation page.
  public var documentationUri: Swift.String = Swift.String()

  /// Output only. Link to external page.
  public var externalUri: Swift.String = Swift.String()

  /// Output only. Description of the resource.
  public var description: Swift.String = Swift.String()

  /// Output only. Cloud storage location of icons etc consumed by UI.
  public var webAssetsLocation: Swift.String = Swift.String()

  /// Output only. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Flag to mark the version indicating the launch stage.
  public var launchStage: LaunchStage = LaunchStage()

  /// Initialize a new instance of `Provider`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Provider().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.Provider"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
