// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Schema of a runtime action.
public struct RuntimeActionSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Name of the action.
  public var action: Swift.String = Swift.String()

  /// Output only. List of input parameter metadata for the action.
  public var inputParameters: [RuntimeActionSchema.InputParameter] = []

  /// Output only. List of result field metadata.
  public var resultMetadata: [RuntimeActionSchema.ResultMetadata] = []

  /// Initialize a new instance of `RuntimeActionSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeActionSchema().with { $0.action = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Metadata of an input parameter.
  public struct InputParameter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of the Parameter.
    public var parameter: Swift.String = Swift.String()

    /// A brief description of the Parameter.
    public var description: Swift.String = Swift.String()

    /// The data type of the Parameter.
    public var dataType: DataType = DataType()

    /// Specifies whether a null value is allowed.
    public var nullable: Swift.Bool = Swift.Bool()

    /// The following field specifies the default value of the Parameter
    /// provided by the external system if a value is not provided.
    public var defaultValue: GoogleCloudWkt.Value? = nil

    /// Initialize a new instance of `InputParameter`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InputParameter().with { $0.parameter = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.RuntimeActionSchema.InputParameter"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Metadata of result field.
  public struct ResultMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of the result field.
    public var field: Swift.String = Swift.String()

    /// A brief description of the field.
    public var description: Swift.String = Swift.String()

    /// The data type of the field.
    public var dataType: DataType = DataType()

    /// Initialize a new instance of `ResultMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResultMetadata().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.RuntimeActionSchema.ResultMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.RuntimeActionSchema"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
