// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// RuntimeConfig is the singleton resource of each location.
/// It includes generic resource configs consumed by control plane and runtime
/// plane like: pub/sub topic/subscription resource name, Cloud Storage location
/// storing schema etc.
public struct RuntimeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. location_id of the runtime location. E.g. "us-west1".
  public var locationId: Swift.String = Swift.String()

  /// Output only. Pub/Sub topic for connd to send message.
  /// E.g. projects/{project-id}/topics/{topic-id}
  public var conndTopic: Swift.String = Swift.String()

  /// Output only. Pub/Sub subscription for connd to receive message.
  /// E.g. projects/{project-id}/subscriptions/{topic-id}
  public var conndSubscription: Swift.String = Swift.String()

  /// Output only. Pub/Sub topic for control plne to send message.
  /// communication.
  /// E.g. projects/{project-id}/topics/{topic-id}
  public var controlPlaneTopic: Swift.String = Swift.String()

  /// Output only. Pub/Sub subscription for control plane to receive message.
  /// E.g. projects/{project-id}/subscriptions/{topic-id}
  public var controlPlaneSubscription: Swift.String = Swift.String()

  /// Output only. The endpoint of the connectors runtime ingress.
  public var runtimeEndpoint: Swift.String = Swift.String()

  /// Output only. The state of the location.
  public var state: RuntimeConfig.State = RuntimeConfig.State()

  /// Output only. The Cloud Storage bucket that stores connector's schema
  /// reports.
  public var schemaGcsBucket: Swift.String = Swift.String()

  /// Output only. The name of the Service Directory service name.
  public var serviceDirectory: Swift.String = Swift.String()

  /// Output only. Name of the runtimeConfig resource.
  /// Format: projects/{project}/locations/{location}/runtimeConfig
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `RuntimeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeConfig().with { $0.locationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of the location.
  public enum State: Codable, Equatable, Sendable {
    /// STATE_UNSPECIFIED.
    case unspecified
    /// INACTIVE.
    @available(*, deprecated)
    case inactive
    /// ACTIVATING.
    @available(*, deprecated)
    case activating
    /// ACTIVE.
    case active
    /// CREATING.
    case creating
    /// DELETING.
    case deleting
    /// UPDATING.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inactive: return 1
      case .activating: return 2
      case .active: return 3
      case .creating: return 4
      case .deleting: return 5
      case .updating: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .inactive: return "INACTIVE"
      case .activating: return "ACTIVATING"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "INACTIVE": self = .inactive
      case "ACTIVATING": self = .activating
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inactive
      case 2: self = .activating
      case 3: self = .active
      case 4: self = .creating
      case 5: self = .deleting
      case 6: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inactive: return try container.encode(1)
      case .activating: return try container.encode(2)
      case .active: return try container.encode(3)
      case .creating: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .updating: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.RuntimeConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
