// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Schema of a runtime entity.
public struct RuntimeEntitySchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Name of the entity.
  public var entity: Swift.String = Swift.String()

  /// Output only. List of fields in the entity.
  public var fields: [RuntimeEntitySchema.Field] = []

  /// Initialize a new instance of `RuntimeEntitySchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeEntitySchema().with { $0.entity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Metadata of an entity field.
  public struct Field: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of the Field.
    public var field: Swift.String = Swift.String()

    /// A brief description of the Field.
    public var description: Swift.String = Swift.String()

    /// The data type of the Field.
    public var dataType: DataType = DataType()

    /// The following boolean field specifies if the current Field acts
    /// as a primary key or id if the parent is of type entity.
    public var key: Swift.Bool = Swift.Bool()

    /// Specifies if the Field is readonly.
    public var readonly: Swift.Bool = Swift.Bool()

    /// Specifies whether a null value is allowed.
    public var nullable: Swift.Bool = Swift.Bool()

    /// The following field specifies the default value of the Field provided
    /// by the external system if a value is not provided.
    public var defaultValue: GoogleCloudWkt.Value? = nil

    /// The following map contains fields that are not explicitly mentioned
    /// above,this give connectors the flexibility to add new metadata
    /// fields.
    public var additionalDetails: GoogleCloudWkt.Struct? = nil

    /// Initialize a new instance of `Field`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Field().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema.Field"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
