// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Ssl config details of a connector version
public struct SslConfigTemplate: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Controls the ssl type for the given connector version
  public var sslType: SslType = SslType()

  /// Boolean for determining if the connector version mandates TLS.
  public var isTlsMandatory: Swift.Bool = Swift.Bool()

  /// List of supported Server Cert Types
  public var serverCertType: [CertType] = []

  /// List of supported Client Cert Types
  public var clientCertType: [CertType] = []

  /// Any additional fields that need to be rendered
  public var additionalVariables: [ConfigVariableTemplate] = []

  /// Initialize a new instance of `SslConfigTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SslConfigTemplate().with { $0.sslType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.SslConfigTemplate"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
